services:
  - type: web
    name: aegis-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false

  - type: web
    name: aegis-frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10000 --server.address 0.0.0.0"
    plan: free
    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: aegis-backend
          property: url
      - key: GOOGLE_API_KEY
        sync: false
